# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Calma < Formula
  desc "♻Calendar for Markdown♻ ...only for Japan!🎌"
  homepage "https://github.com/ddddddO/calma"
  version "1.2.9"
  license "BSD-2-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ddddddO/calma/releases/download/v1.2.9/calma_darwin_x86_64.tar.gz"
      sha256 "28379f5d9e9bc0747fb6f6d30ea6b79ad1719133e503d20525993495108b0c40"

      def install
        bin.install "calma"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ddddddO/calma/releases/download/v1.2.9/calma_darwin_arm64.tar.gz"
      sha256 "593bdfa3c4b006e8012eb6018131941bb355924381ec14bfc41d03915ac9b9d0"

      def install
        bin.install "calma"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ddddddO/calma/releases/download/v1.2.9/calma_linux_x86_64.tar.gz"
      sha256 "64fd778cff376d9590cf0b24c190d6211871da0c6ca14e00110ce968446dcd9f"

      def install
        bin.install "calma"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ddddddO/calma/releases/download/v1.2.9/calma_linux_arm64.tar.gz"
      sha256 "9ab08576ad265e9c2080a299156eef33e68ddc416dac088fc23c7c3122946911"

      def install
        bin.install "calma"
      end
    end
  end
end
