# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Calma < Formula
  desc "♻Calendar for Markdown♻ ...only for Japan!🎌"
  homepage "https://github.com/ddddddO/calma"
  version "1.2.3"
  license "BSD-2-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ddddddO/calma/releases/download/v1.2.3/calma_darwin_x86_64.tar.gz"
      sha256 "84a140b2136ebd059cc81ca2729b92847441f2344b3d0596f4b7fe8f59890185"

      def install
        bin.install "calma"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ddddddO/calma/releases/download/v1.2.3/calma_darwin_arm64.tar.gz"
      sha256 "4df470a22978673afca226be45d04ea1ca1a60d6d9869f83c4301b2c9ab09a9f"

      def install
        bin.install "calma"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ddddddO/calma/releases/download/v1.2.3/calma_linux_arm64.tar.gz"
      sha256 "11411da6dfa25154d10ff3d1b4e8c9bb13e741c6749de21a829b3a12f19fd8f3"

      def install
        bin.install "calma"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ddddddO/calma/releases/download/v1.2.3/calma_linux_x86_64.tar.gz"
      sha256 "08238010d9087087b4810277992614ee3a0311e9a67a9b0556d8f0eeaa5c0958"

      def install
        bin.install "calma"
      end
    end
  end
end
