# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gtree < Formula
  desc "Output tree🌳 or Make directories(files)📁 from Markdown."
  homepage "https://github.com/ddddddO/gtree"
  version "1.7.17"
  license "BSD-2-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ddddddO/gtree/releases/download/v1.7.17/gtree_darwin_x86_64.tar.gz"
      sha256 "ea656733f892504ea6774b4f0857c45d80379aba8f707aabe872d71e2aa70852"

      def install
        bin.install "gtree"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ddddddO/gtree/releases/download/v1.7.17/gtree_darwin_arm64.tar.gz"
      sha256 "9cc40a9c6b6908dca8a6e4c7ee7f9ccfed8d5bc11fcf1cf2ea091ab5794bc889"

      def install
        bin.install "gtree"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ddddddO/gtree/releases/download/v1.7.17/gtree_linux_x86_64.tar.gz"
      sha256 "309892cb33ae96f3db85f9bfdedd71f3e9f3ca1f883fd0f2be65deeec8ca89ab"

      def install
        bin.install "gtree"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ddddddO/gtree/releases/download/v1.7.17/gtree_linux_arm64.tar.gz"
      sha256 "e87bb0ab6855a905b3812587b345ec46191bad23b2e24a3883dd747bd8395aae"

      def install
        bin.install "gtree"
      end
    end
  end
end
