# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gtree < Formula
  desc "Output tree🌳 or Make directories(files)📁 from Markdown."
  homepage "https://github.com/ddddddO/gtree"
  version "1.7.51"
  license "BSD-2-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ddddddO/gtree/releases/download/v1.7.51/gtree_darwin_x86_64.tar.gz"
      sha256 "0e0cf8278ba9adc38fc442d68db43afff33f3d233219abcfe605c4c712f81dfb"

      def install
        bin.install "gtree"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ddddddO/gtree/releases/download/v1.7.51/gtree_darwin_arm64.tar.gz"
      sha256 "09c3148b4c9b98f3d45229d6383a52a54f2b027f159bcc5b556d22a5f3a54959"

      def install
        bin.install "gtree"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ddddddO/gtree/releases/download/v1.7.51/gtree_linux_arm64.tar.gz"
      sha256 "344c60a6ab7d803e7ceada40cf29ed6db2edfc6080a0d04be929b1f52303b6d4"

      def install
        bin.install "gtree"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ddddddO/gtree/releases/download/v1.7.51/gtree_linux_x86_64.tar.gz"
      sha256 "096907b4135df36aa175bf4201527dc67aa95183f25dc78d66e344498a73dbf8"

      def install
        bin.install "gtree"
      end
    end
  end
end
