# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gtree < Formula
  desc "Output tree🌳 or Make directories(files)📁 from Markdown."
  homepage "https://github.com/ddddddO/gtree"
  version "1.7.45"
  license "BSD-2-Clause"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ddddddO/gtree/releases/download/v1.7.45/gtree_darwin_arm64.tar.gz"
      sha256 "5cc6b3c436b35300fb529b7963d56cce70ed8d977e02071ad15a35712c1d6ddb"

      def install
        bin.install "gtree"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ddddddO/gtree/releases/download/v1.7.45/gtree_darwin_x86_64.tar.gz"
      sha256 "52db528db0f173a5dd8a4889435a0144debc42621d2656255730944e10402739"

      def install
        bin.install "gtree"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ddddddO/gtree/releases/download/v1.7.45/gtree_linux_arm64.tar.gz"
      sha256 "33272b664973f9c78e9a2b0cea28a2d426aafdba7350ad7a6d96dc23938c7b21"

      def install
        bin.install "gtree"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ddddddO/gtree/releases/download/v1.7.45/gtree_linux_x86_64.tar.gz"
      sha256 "3a4d386aa0f6197499b35ae052d937043245bf929f545e67f6b088d2ec86b4f9"

      def install
        bin.install "gtree"
      end
    end
  end
end
