# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kaisekisan < Formula
  desc "Kaisekisan"
  homepage "https://github.com/ddddddO/kaisekisan"
  version "0.1.4"
  license "BSD-2-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ddddddO/kaisekisan/releases/download/v0.1.4/kaisekisan_darwin_x86_64.tar.gz"
      sha256 "fabd3866ca2e53fc0188d0db4917e4b855144174e7837ac81e0f2c5250a01f20"

      def install
        bin.install "kaisekisan"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ddddddO/kaisekisan/releases/download/v0.1.4/kaisekisan_darwin_arm64.tar.gz"
      sha256 "75ad2c1d39e24b8bbdfb4387825743c7a1686c76d21dc1d160ba26d4ad411977"

      def install
        bin.install "kaisekisan"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ddddddO/kaisekisan/releases/download/v0.1.4/kaisekisan_linux_x86_64.tar.gz"
      sha256 "824671160750df8efe3200d3e7b9c31c7c06cd61c194766eba296cd309b51acd"

      def install
        bin.install "kaisekisan"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ddddddO/kaisekisan/releases/download/v0.1.4/kaisekisan_linux_arm64.tar.gz"
      sha256 "a42520fd7ba0076d9f532698e76a8284d39bb8cfe6058da1c17354f024f335c3"

      def install
        bin.install "kaisekisan"
      end
    end
  end
end
