# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kaisekisan < Formula
  desc "Kaisekisan"
  homepage "https://github.com/ddddddO/kaisekisan"
  version "0.1.2"
  license "BSD-2-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ddddddO/kaisekisan/releases/download/v0.1.2/kaisekisan_darwin_x86_64.tar.gz"
      sha256 "d16794a00a98679e383103e7058a6581c80035a6ca70a4c67d29767b1f72566e"

      def install
        bin.install "kaisekisan"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ddddddO/kaisekisan/releases/download/v0.1.2/kaisekisan_darwin_arm64.tar.gz"
      sha256 "d4a61c8c820d88a32b2c8a9d8ddf8b4d1b541bfc1d27a7efaba709186e004e3a"

      def install
        bin.install "kaisekisan"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ddddddO/kaisekisan/releases/download/v0.1.2/kaisekisan_linux_arm64.tar.gz"
      sha256 "c11111264add8f261808552ee028af40e7e60e46cc5d307fa27311ca89576d96"

      def install
        bin.install "kaisekisan"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ddddddO/kaisekisan/releases/download/v0.1.2/kaisekisan_linux_x86_64.tar.gz"
      sha256 "9a144732db417f729702f4ed4ebac36103384a7e8a179716ccced8ca20c7972b"

      def install
        bin.install "kaisekisan"
      end
    end
  end
end
