# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ppaid < Formula
  desc "Tool that aids PHPUnit and PCOV"
  homepage "https://github.com/ddddddO/ppaid"
  version "1.0.0"
  license "BSD-2-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ddddddO/ppaid/releases/download/v1.0.0/ppaid_darwin_amd64.tar.gz"
      sha256 "70578ade1ef7141b5c663bcaeb4f66883d579d98bb55590c4ffa22c104616037"

      def install
        bin.install "ppaid"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ddddddO/ppaid/releases/download/v1.0.0/ppaid_darwin_arm64.tar.gz"
      sha256 "db0804fb63d9180513e1641139b4464cdda9703dc5b274d6976a5899b3a6490a"

      def install
        bin.install "ppaid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ddddddO/ppaid/releases/download/v1.0.0/ppaid_linux_amd64.tar.gz"
      sha256 "1094e2ddc01141b7958efc645853a64bc84e1011de32a311d77dab6fae28338b"
      def install
        bin.install "ppaid"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ddddddO/ppaid/releases/download/v1.0.0/ppaid_linux_arm64.tar.gz"
      sha256 "faa0c48aba0b8d54376c00de7ffc22b624aff95bd9c5fbf141e050339995875a"
      def install
        bin.install "ppaid"
      end
    end
  end
end
