# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ppaid < Formula
  desc "Tool that aids PHPUnit and PCOV"
  homepage "https://github.com/ddddddO/ppaid"
  version "1.1.1"
  license "BSD-2-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ddddddO/ppaid/releases/download/v1.1.1/ppaid_darwin_amd64.tar.gz"
      sha256 "6b9d5f40bd14341472111281d66a321939016aa9b67beb91b284770dc3691214"

      def install
        bin.install "ppaid"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ddddddO/ppaid/releases/download/v1.1.1/ppaid_darwin_arm64.tar.gz"
      sha256 "b5d73861af175ef944a7e10a59b9e3cb096bc9e1225ab777caa65b1bc7ad08ff"

      def install
        bin.install "ppaid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ddddddO/ppaid/releases/download/v1.1.1/ppaid_linux_amd64.tar.gz"
      sha256 "8aea2b988a6108250e99ec3a8f4cc77820e1a88d9a73e825a7e8918d4a6278de"
      def install
        bin.install "ppaid"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ddddddO/ppaid/releases/download/v1.1.1/ppaid_linux_arm64.tar.gz"
      sha256 "1df440737fdb1d3298caca206f1ad99d9fc04f1fae644a9e7a6e86d9a340b983"
      def install
        bin.install "ppaid"
      end
    end
  end
end
