# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ppaid < Formula
  desc "Tool that aids PHPUnit and PCOV"
  homepage "https://github.com/ddddddO/ppaid"
  version "1.0.1"
  license "BSD-2-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ddddddO/ppaid/releases/download/v1.0.1/ppaid_darwin_amd64.tar.gz"
      sha256 "5e0a6d7e18760fb03e6e3ef99e5c48b7ca7795ae677fb7809b9c6a0b1d724d7f"

      def install
        bin.install "ppaid"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ddddddO/ppaid/releases/download/v1.0.1/ppaid_darwin_arm64.tar.gz"
      sha256 "a56c32a27e57e3a682ce35e8687ab56e802224ab4316af2041def6f1ec788c10"

      def install
        bin.install "ppaid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ddddddO/ppaid/releases/download/v1.0.1/ppaid_linux_amd64.tar.gz"
      sha256 "41b545e2cf3d1c441dd7a5e90b37a9e18c0968c31e61cdede1444330e619996c"
      def install
        bin.install "ppaid"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ddddddO/ppaid/releases/download/v1.0.1/ppaid_linux_arm64.tar.gz"
      sha256 "d79447d2652586f33d60f1c5471e841b60afa77eb143e83c204a10ebb7e9d32d"
      def install
        bin.install "ppaid"
      end
    end
  end
end
