# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ps2 < Formula
  desc "🎮 phP Serialize() To xxxx (e.g. JSON)"
  homepage "https://github.com/ddddddO/ps2"
  version "1.0.10"
  license "BSD-2-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ddddddO/ps2/releases/download/v1.0.10/ps2_darwin_amd64.tar.gz"
      sha256 "cc035e05bcfddafdfca72f726b5bb08b445d1fe9e666608658ad785679e2797d"

      def install
        bin.install "ps2"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ddddddO/ps2/releases/download/v1.0.10/ps2_darwin_arm64.tar.gz"
      sha256 "d1ce3932b859c5c4797ebf51447559470b3ea91317fb6e0aa54485eb38548952"

      def install
        bin.install "ps2"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/ddddddO/ps2/releases/download/v1.0.10/ps2_linux_amd64.tar.gz"
      sha256 "21a299591f705774c4d87e5f27a6330f96ac7cac7cd5cb192612d7b392566e70"
      def install
        bin.install "ps2"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/ddddddO/ps2/releases/download/v1.0.10/ps2_linux_arm64.tar.gz"
      sha256 "fc35bd3e2e1c8e6b6bcaa7a8e9a1de922e17330381946b94c495ac480d37289c"
      def install
        bin.install "ps2"
      end
    end
  end
end
