# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Puco < Formula
  desc "Tool that aids PHPUnit and PCOV"
  homepage "https://github.com/ddddddO/puco"
  version "1.1.3"
  license "BSD-2-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ddddddO/puco/releases/download/v1.1.3/puco_darwin_amd64.tar.gz"
      sha256 "8d0c8356d094ae8547c4ac52d6b8999e29cc1b3c9ed91a44c6c010b2d8c29932"

      def install
        bin.install "puco"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ddddddO/puco/releases/download/v1.1.3/puco_darwin_arm64.tar.gz"
      sha256 "9eac51437bbdf743aa5293c7b8903a974c93b229225d0327200937cbcf3ff840"

      def install
        bin.install "puco"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ddddddO/puco/releases/download/v1.1.3/puco_linux_amd64.tar.gz"
      sha256 "6da843c817c63e540a21414a67f99616175e2978f0391bc247b9a7ca687d921e"
      def install
        bin.install "puco"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ddddddO/puco/releases/download/v1.1.3/puco_linux_arm64.tar.gz"
      sha256 "5c80e9ab1e11c710de474484b25ee476fa7594e39e57315e31b6e60c2556a072"
      def install
        bin.install "puco"
      end
    end
  end
end
