# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Puco < Formula
  desc "Tool that aids PHPUnit and PCOV"
  homepage "https://github.com/ddddddO/puco"
  version "1.1.4"
  license "BSD-2-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ddddddO/puco/releases/download/v1.1.4/puco_darwin_amd64.tar.gz"
      sha256 "80fbdffe71a2e35c318e986dc1a3fda507ca9f50c75475eddfb398b291298659"

      def install
        bin.install "puco"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ddddddO/puco/releases/download/v1.1.4/puco_darwin_arm64.tar.gz"
      sha256 "7442a7c2c89ecab1078f552cfab5563ac6e5a70a05c6beb7ff377be7f508bf57"

      def install
        bin.install "puco"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ddddddO/puco/releases/download/v1.1.4/puco_linux_amd64.tar.gz"
      sha256 "70ab4b16d35c951c54bab7527ee147c478abe1a8178f0889b1e6fa0480a583ac"
      def install
        bin.install "puco"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ddddddO/puco/releases/download/v1.1.4/puco_linux_arm64.tar.gz"
      sha256 "bb17ab4a943ab4d74f448f4ade7b0a7ca9911ff11788fec10068d9c571a51848"
      def install
        bin.install "puco"
      end
    end
  end
end
